# Generated by Django 3.2.9 on 2021-11-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='name',
            new_name='Advisor_Name',
        ),
        migrations.RenameField(
            model_name='advisor',
            old_name='advisor_id',
            new_name='Advisor_id',
        ),
        migrations.RenameField(
            model_name='bookacall',
            old_name='advisor_id',
            new_name='Advisor_id',
        ),
        migrations.RenameField(
            model_name='bookacall',
            old_name='booking_id',
            new_name='Booking_id',
        ),
        migrations.RenameField(
            model_name='bookacall',
            old_name='booking_a_time',
            new_name='Booking_time',
        ),
    ]
