# Generated by Django 3.2.9 on 2021-11-13 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20211112_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='user',
        ),
    ]
