# Generated by Django 3.2.9 on 2021-11-14 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_advisor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advisor',
            old_name='PhotoUrl',
            new_name='Avisor_Photo_Url',
        ),
    ]
